/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        TestCase1 test1 = new TestCase1();
        //TODO: call your test case functions one after other here
        //test1.testCase01();
        //test1.testCase02();
        test1.testCase01();
       // tests.testCase01();
        //tests.testCase02();
       // tests.testCase03();
       // tests.testCase04();
       //tests.testCase05();
       // tests.testCase06();
       // tests.testCase07();
       // tests.testCase08();
        //tests.testCase09();
        //tests.testCase10();
       //tests.testCase11();
        //tests.testCase12();
        //tests.testCase13();
       // tests.testCase14();
        //tests.testCase15();
        //tests.testCase16();
       // tests.testCase17();
       //tests.testCase18();
       //tests.testCase24();
        //END Tests


        test1.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
